name: CI - Playwright API Tests

# runs-on: ubuntu-latest
#   to oznacze, że kiedy GitHub Actions uruchamia ten workflow,
#   zadanie (job:) będzie uruchamiane na maszynie z Linuxem
# steps:
# kroki w ramach tego zadania, ich rodzaje to:
#   - name: <nazwa kroku> - opisowy tytuł kroku, który będzie widoczny w logach
#   - run: <polecenie> - uruchamia polecenie w terminalu maszyny, na której działa workflow
#   - uses: <nazwa akcji> - używa gotowej akcji (action) z GitHub Marketplace, która wykonuje określone zadanie, 
#         np. checkout kodu, setup Node.js, załądowanie artefaktów itp.
#   - if: <warunek> - warunek wykonania danego kroku
#   W ramach 1 kroku można uruchamiać polecenia (run), jak też używać gotowych akcji (uses),
# on: - mówi co warunkuje uruchomienie workflow ma być uruchamiany, np. na push, pull request, wg harmonogramu itp.
#   tutaj: workflow będzie uruchamiany 
#   1. na push do dowolnej gałęzi (branches: ["**"]) 
#   2. na pull request, czyli gdy ktoś tworzy pull request do tego repozytorium
# oraz na pull request.
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # instalowanie przeglądarek Playwright jest potrzebne, nawet gdy testowane jest tylko API, 
      #   - Playwright może używać tych przeglądarek m.in. do generowania raportów, 
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test

      # if: always()  - Przesyłanie raportu nawet jeśli testy się nie powiodą
      # uses: actions/upload-artifact@v4 
      #               - wbudowana akcja GitHub 
      #     do przesyłania artefaktów (np. raportów, wyników testów) z workflow do repozytorium GitHub,
      #     => można je później pobrać i przeanalizować.
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14
      # Przesyłanie surowych wyników testów, raporty w takiej formie
      #   można ich użyć gdy chcemy zintegrować wyniki testów z innymi narzędziami, 
      #     np. do analizy wyników testów, do integracji z CI/CD.
      - name: Upload raw Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 14